### ISSUE TITLE
This code contains virus signatures, author is knowingly trying to spread viruses and malware to unsuspecting users

### ISSUE THREAD

**Issue by hazeyez** [alt-magick/Correspondence#3]
> There is no virus in the code, or executable. 

From issue https://github.com/alt-magick/Correspondence/issues/2#issue-2412692670

Author knowingly is trying to spread a virus with this code and executable. He ripped the code off GPT to begin with and tried to copyright the code. Then after knowing it was flagged for multiple virus signatures he has done nothing to modify it. In fact, he is well known on an IRC network to try to create and spread malware. Then he was bragging yesterday about trying to promote this file with SEO to unsuspecting users. 

What an absolute joke and sham, to try and claim and try to associate yourself with a "hacker" community when this is the pinnacle of your capability, and your only intention is to cause actual harm to unsuspecting people and users. 

You should delete this whole repository.

Here is the exact "correspondence.exe" file he uploaded to VirusTotal himself and the link he shared - which you can see from the IRC chat screenshot below that he knows it contains virus signatures:

https://www.virustotal.com/gui/file/f217f00ce0df15713dd5188360420cd7c2e067f0b041e073476225986db72a6d/detection

![street_virus](https://github.com/user-attachments/assets/93959a58-1913-4dfb-a2af-aef4f48e557a)

Here is the .exe file from his main repository branch from commit # 26a1123 which is the most recent upload of the .exe file in this repository, and the compiled version of the .cpp code uploaded - which I downloaded and scanned myself:

https://www.virustotal.com/gui/file/1604c17dc824a5ce01b2d66093b77ef523734f72e011cf5f37aead9d25d79b1c/detection

**I suggest everyone click the "Details" and other tabs on these links, they can see the file hashes and file names.**

Author has made zero effort to try and modify or fix this code before claiming that it is harmless. Truly careless and reckless behavior.

**Comment by alt-magick** [comment]
This program has no virus, or any kind of malware.
