### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by oxagast** [alt-magick/Correspondence#4]
Author knowingly spreading malware.  This detects as a virus.

**Comment by oxagast** [comment]
14:15 <    street> https://github.com/alt-magick/Correspondence/
14:15 <    street> My source is there
14:16 <    street> I think someone complained and whined about it
14:17 <    street> I used chatgpt
14:18 <    street> I downloaded the exe and ran a scan just now, and it didn't detect it
14:22 <    street> Or there is no malware, ?
14:22 <    street> Yeah I didn't cut and paste anything
14:23 <    street> The program is kind of an encryption tool in a sense
14:24 <    street> It is a text editor that remaps keys in its window
14:28 <    street> What are you talking about?
14:28 <   hazeyez> [02:15:46pm] <street> https://github.com/alt-magick/Correspondence/
14:28 <    street> That is code I wrote myself with chatgpt
14:29 <    street> I just deleted all of my code and compiled it again from the repo, and its not being flagged
14:29 <    street> But virus total is a good idea
14:31 <    street> https://www.virustotal.com/gui/file/55e2a207719bde54d51b904875a21dce4ab198a7d33b27493b2efd00fa75b6a3?nocache=1
14:34 <    street> So it says 4/74 flagged it
14:35 <    street> I wish it gave us more info about that
14:37 <    street> oxagast: it is good to have you back!
14:38 <    street> Nope, no XML
14:38 <    street> The source code is on the git page
14:38 <    street> main.cpp
14:38 <    street> I wrote it so that it compiles as a empty console program
14:39 <    street> Its a win api program
14:41 <    street> I compiled it as a release
14:41 <    street> Is that what you mean?
14:41 <    street> Instead of debug
14:44 <    street> Well after I deleted my C++ repo, and recompiled it I don't get any virus flags. Even when I download from github.
14:45 <    street> idk, but thanks for the support hazeyez
14:46 <    street> oxagast: what about obfuscating the source code?
14:46 <    street> yeah
14:47 <    street> I wonder if there are any good books on that
14:58 <    street> Oo right
15:01 <    street> Have you guys tried running my program?
15:02 <    street> ok
15:05 <    street> Sometimes I think a program can get flagged by a person
15:05 <    street> Oo, Its my own notepad program
15:06 <    street> No its not called notepad.exe
15:07 <    street> Phreaked left after you got banned
15:07 <    street> Now he's back
15:08 <@ Phreaked> street, thanks captain obvious
15:09 <      zyme> wow the time mismatch must be bad unless Phreaked could type I don't think that's the case in under a second after street said he left..
15:11 <    street> Hi zyme
15:13 <@ Phreaked> street, <street> Phreaked left after you got banned. I wage you can't prove this...
15:13 <    street> Maybe not
15:15 <@ Phreaked> this ones for you street https://www.youtube.com/watch?v=Xm3M-8ypwus
15:16 <    street> ok, listening
15:21 <    street> When does it start?
15:22 <@ Phreaked> If you don't know, street.. get to know http://www.hope.net/
15:23 <    street> Phreaked: this video is good
15:25 <    street> You guys know what a WIP is?
15:26 <    street> Hi CerebraNet
15:26 < CerebraNe> HI street
15:28 <    street> Guess whos back?
15:29 <    street> .seen oxagast
15:37 <    street> How big is your hard drive?
15:46 <    street> You got to give us a chance to listen to the last ones
15:47 <    street> I remember when weev came in here
15:52 <@ Phreaked> street, this ones for you
15:53 <    street> got it
16:34 <    street> Funny you should say that
16:34 <    street> I got a message from google saying someone used my password today
16:35 <    street> I think I exposed my hash at some point
16:35 <    street> So yes I changed it
16:35 <    street> all of them
16:36 <    street> Password managers can help
16:36 <    street> You could keep a list in your wallet
16:42 <    street> We have to do something, with the power of GPUs they can crack anything
16:44 <    street> Nirvana's Bleach is still one of the best albums ever made
16:44 <    street> from 1985
16:45 <      d0pe> street, is there a connection with passwords
17:03 <    street> I was pwned too
17:06 <    street> And here I go hosting a encrypted file with my pwned password as the key
17:06 <    street> Making it really easy for them
17:11 <    street> You just have to hope hackers aren't malicious
17:12 <    street> Where do you get the data breach passwords?
17:14 <        Oo> street
17:28 <    street> hazeyez: I think its underground right no
17:28 <    street> now
17:29 <    street> I just want to see if my old password is in it
17:42 <    street> I'll just assume its in there
18:11 <    street> HOPE starts at 9:50 AM
19:41 <    street> hello 2600
22:19 <    street> Everyone ready for HOPE?
02:03 <    street> Anyone online?
02:12 <      zyme> hi street
02:16 <    street> zyme: hello
02:16 <    street> I'm still battling windows defender
02:17 <    street> I'm not sure
02:17 <    street> I wish I knew
02:17 <    street> I wrote a nice program
02:17 <    street> And it thinks its a virus
02:18 <    street> It doesn't say really
02:18 <    street> Just deltes my program
02:18 <    street> deletes
02:20 <    street> Yeah?
02:20 <    street> It doesn't say much
02:24 <    street> I run scans and it doesn't find a virus
02:24 <    street> but then out of nowhere it flags this code
02:25 <    street> I feel like its personal
02:26 <    street> Is there a way to make defender look at one file?
02:28 <    street> idk zyme
02:29 <    street> Hmm
02:35 <    street> https://www.virustotal.com/gui/file/f217f00ce0df15713dd5188360420cd7c2e067f0b041e073476225986db72a6d/detection

**Comment by alt-magick** [comment]
There is no virus
